### PR TITLE
Upgrade to sdk v3

### PR DESCRIPTION
**Pull request by mariusGundersen**
I managed to convert the app to v3, at least for the temperature and humidity sensors that I have. There are probably some things that I have missed, but at least now it works

### CODE REVIEW

**Comment by nlrb** [comment]
Nice work Marius! I've made some small additions and will submit this version to the apps store.

**Comment by mariusGundersen** [comment]
Great, thanks! I misunderstood the node_modules, I realized later that the files were included in the repo. Sorry about that

**Comment by lovegren22** [comment]
Any eta on when tis app will reach the store? Thanks for the work.

**Comment by lovegren22** [comment]
I must be sleepy or something, how do I find it? 😵‍💫😴
https://homey.app/sv-se/app/com.weather-sensors/Wireless-Weather-Sensors/ 
Says it’s not available for HP23
Is it because I am in sv-se app store?

**Comment by pjmpessers** [comment]
https://homey.app/sv-se/app/com.weather-sensors/Wireless-Weather-Sensors/test




Verzonden vanaf mijn Galaxy


-------- Oorspronkelijk bericht --------
Van: lovegren22 ***@***.***>
Datum: 08-05-2023 20:44 (GMT+01:00)
Aan: "nlrb/com.weather-sensors" ***@***.***>
Cc: Subscribed ***@***.***>
Onderwerp: Re: [nlrb/com.weather-sensors] Upgrade to sdk v3 (PR #102)


I must be sleepy or something, how do I find it? 😵‍💫😴
https://homey.app/sv-se/app/com.weather-sensors/Wireless-Weather-Sensors/
Says it’s not available for HP23
Is it because I am in sv-se app store?

**Comment by lovegren22** [comment]
Many thanks 🙏

**Comment by pjmpessers** [comment]
Glad to help.



Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: lovegren22 ***@***.***>
Datum: 08-05-2023 20:50 (GMT+01:00)
Aan: "nlrb/com.weather-sensors" ***@***.***>
Cc: Pieter ***@***.***>, Comment ***@***.***>
Onderwerp: Re: [nlrb/com.weather-sensors] Upgrade to sdk v3 (PR #102)


Many thanks 🙏

**Pull request merged**
